package cellsociety.view.components;

import cellsociety.model.util.SimulationTypes.SimType;
import cellsociety.model.util.XMLData;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class RandomSimulationGenerator {
  /**
   * Creates a GAME OF LIFE simulation with random cell state layout. Code generated by ChatGPT.
   */
  public static XMLData createRandomGameOfLifeXML() {
    XMLData randomXMLData = new XMLData();

    // Set simulation metadata
    randomXMLData.setType(SimType.GAMEOFLIFE);
    randomXMLData.setTitle("Game of Life Random Simulation");
    randomXMLData.setAuthor("Cell Society");
    randomXMLData.setDescription("This is a randomly generated simulation of Conway's Game of Life.");

    // Set grid dimensions
    int numRows = 50;
    int numCols = 75;
    randomXMLData.setGridRowNum(numRows);
    randomXMLData.setGridColNum(numCols);

    // Initialize cell states randomly
    ArrayList<Integer> cellStateList = new ArrayList<>();
    Random random = new Random();

    for (int i = 0; i < numRows * numCols; i++) {
      // Randomly assign ALIVE or DEAD
      int state = random.nextBoolean() ? 1 : 0;
      cellStateList.add(state);
    }

    randomXMLData.setCellStateList(cellStateList);

    // Set default parameters (Game of Life does not require any, but included for completeness)
    Map<String, Double> parameters = new HashMap<>();
    randomXMLData.setParameters(parameters);

    return randomXMLData;
  }
}
