package cellsociety.view.components;

import cellsociety.model.util.SimulationTypes.SimType;
import cellsociety.model.util.XmlData;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

/**
 * Creates a GAME OF LIFE simulation with random cell state layout. Code generated by ChatGPT.
 */
public class RandomSimulationGenerator {

  /**
   * Creates a GAME OF LIFE simulation with random cell state layout. Code generated by ChatGPT.
   */
  public static XmlData createRandomGameOfLifeXml() {
    XmlData randomXmlData = new XmlData();

    // Set simulation metadata
    randomXmlData.setType(SimType.GameOfLife);
    randomXmlData.setTitle("Game of Life Random Simulation");
    randomXmlData.setAuthor("Cell Society");
    randomXmlData.setDescription(
        "This is a randomly generated simulation of Conway's Game of Life.");

    // Set grid dimensions
    int numRows = 50;
    int numCols = 75;
    randomXmlData.setGridRowNum(numRows);
    randomXmlData.setGridColNum(numCols);

    // Initialize cell states randomly
    ArrayList<Integer> cellStateList = new ArrayList<>();
    Random random = new Random();

    for (int i = 0; i < numRows * numCols; i++) {
      // Randomly assign ALIVE or DEAD
      int state = random.nextBoolean() ? 1 : 0;
      cellStateList.add(state);
    }

    randomXmlData.setCellStateList(cellStateList);

    // Set default parameters (Game of Life does not require any, but included for completeness)
    Map<String, Double> parameters = new HashMap<>();
    randomXmlData.setParameters(parameters);

    return randomXmlData;
  }
}
